//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace MonoDevelop.VersionControl.Git
{
	public partial class CloneRepositoryDialog : Gtk.Dialog
	{
		protected virtual void Cancel_ButtonPress (object sender, Gtk.ButtonPressEventArgs args)
		{
			HideAll ();
		}
		
		public CloneRepositoryDialog ()
		{
			this.Build ();
		}
		
		public string RepositoryPath 
		{
			get { return entryRepositoryPath.Text; }
		}
		
		public string WorkingDirectory 
		{
			get { return editFolderEntry.Path; }
		}
		
		public string OriginName 
		{
			get { return entryOriginName.Text; }
		}
	}
}